Fix extra context exception (#12)
## Background and Change
* Avoid
```
  File "/Users/jessicacovington/prj/allowedflare/django_allowedflare/__init__.py", line 80, in get
    self.extra_context['allowedflare_message'] = message
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
```
* Also minor tooling updates

## Testing
Tested in Chrome by navigating to http://localhost:8001/admin/ and
http://localhost:8001/explore/, without `CF_Authorization` set, and with
it set to a valid JWT.

## Followup and Open Questions
* Write unit tests for the Django classes and functions
* When is extra_context None and when is it not?